name: Ci-integration

on:
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Set up Python 3.10
        run: uv python install

      - name: Install dependencies
        run: uv sync --dev

      - name: Run tests
        run: uv run pytest tests/integration

      - name: Set up docker build
        run: docker build -t test-build .

      - name: Run Container
        run: docker run -d --name app -p 8000:8000 test-build

      - name: Smoke test
        run: |
          sleep 2
          curl -f http://localhost:8000/docs

      - name: Stop container
        if: always()
        run: docker rm -f app
